### ISSUE TITLE
Drakengard aircraft

### ISSUE THREAD

**Issue by Azekthi** [canmom/canmom.github.io#5]
https://github.com/canmom/canmom.github.io/blob/master/_posts/nier/2020-04-22-dod-part-2.md

The secret "dragon" aircraft is actually the Sukhoi Su-47, not the Sukhoi Su-37. I know it's a nitpick but I figured I should point it out regardless 😛

**Comment by canmom** [comment]
Hello!
Glad my post reached the intersection of 'people who know about old Soviet aeroplanes' and 'people who read long articles about Drakengard'! I'll fix that up later today ^^

**Comment by Azekthi** [comment]
Haha, to be honest I don't play Drakengard or NieR but I always end up spending hours reading about their lore (and I play Final Fantasy XIV which is having some collaboration raids). I was trying to search the web to see if the JASDF 303rd Flight Squadron really existed [(it does)](https://en.wikipedia.org/wiki/303rd_Tactical_Fighter_Squadron_(JASDF)) and stumbled across your article. I'm a massive fan of Ace Combat, which is the only reason I could identify the Su-47. Thanks for the quick response :3
